[profile.default]
solc_version = '0.8.13'
optimizer = true
optimizer_runs = 5000
out = 'artifacts'
test = 'test'
src = 'contracts'
libs = ['node_modules', 'lib']
gas_reports = ['*']

fs_permissions = [{ access = "read", path = "./artifacts"}]


# [profile.default.fmt]
# line_length = 120
# bracket_spacing = true
# wrap_comments = true
# number_underscore = "thousands"