[profile.default]
solc_version = '0.8.13'
optimizer = true
optimizer_runs = 5000
out = 'dist/artifacts'
test = 'test'
src = 'contracts'
libs = ['lib']
gas_reports = ['*']

fs_permissions = [{ access = "read", path = "./dist/artifacts"}]

